from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Iterable

import yaml

from .service_store import ServiceDefinition, ServiceStoreError


GENERATED_HEADER = (
    "# AUTO-GENERATED BY LOCAL SERVICE HUB v0.4.\n"
    "# Source of truth: services.json. Do not edit this file manually.\n"
)


def process_id_for(service_id: str, runtime_id: str = "main") -> str:
    base = f"service_{service_id}"
    return base if runtime_id == "main" else f"{base}__{runtime_id}"


def process_ids_for(service: ServiceDefinition) -> list[str]:
    return [process_id_for(service.id, item.id) for item in service.items()]


class ProcessComposeConfigGenerator:
    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        self.temp_path = self.path.with_name(f"{self.path.name}.tmp")
        self.rollback_path = self.path.with_name(f"{self.path.name}.rollback")
        self._recover_interrupted_commit()

    def _recover_interrupted_commit(self) -> None:
        try:
            if self.rollback_path.exists():
                os.replace(self.rollback_path, self.path)
            self.temp_path.unlink(missing_ok=True)
        except OSError as exc:
            raise ServiceStoreError(f"恢复未完成的 Process Compose 配置事务失败：{exc}") from exc

    def build(self, services: Iterable[ServiceDefinition]) -> dict[str, Any]:
        processes: dict[str, Any] = {}
        for service in services:
            if not service.enabled:
                continue
            for item in service.items():
                description = service.name
                if len(service.items()) > 1:
                    description = f"{service.name} · :{item.port}"
                processes[process_id_for(service.id, item.id)] = {
                    "description": description,
                    "command": item.command,
                    "working_dir": service.working_dir,
                    "namespace": "registered",
                    "disabled": True,
                }
        return {"version": "0.5", "processes": processes}

    def prepare(self, services: Iterable[ServiceDefinition]) -> Path:
        payload = self.build(services)
        encoded = GENERATED_HEADER + yaml.safe_dump(
            payload,
            allow_unicode=True,
            sort_keys=False,
            default_flow_style=False,
            width=4096,
        )
        try:
            parsed = yaml.safe_load(encoded)
            if not isinstance(parsed, dict) or not isinstance(parsed.get("processes"), dict):
                raise ValueError("generated YAML is missing the processes mapping")
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.temp_path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(encoded)
                handle.flush()
                os.fsync(handle.fileno())
            yaml.safe_load(self.temp_path.read_text(encoding="utf-8"))
            return self.temp_path
        except Exception as exc:
            try:
                self.temp_path.unlink(missing_ok=True)
            except OSError:
                pass
            raise ServiceStoreError(f"生成 Process Compose 配置失败：{exc}") from exc

    def commit_prepared(self) -> Path:
        if not self.temp_path.exists():
            raise ServiceStoreError("没有已准备的 Process Compose 配置")
        had_current = self.path.exists()
        try:
            self.rollback_path.unlink(missing_ok=True)
            if had_current:
                os.replace(self.path, self.rollback_path)
            os.replace(self.temp_path, self.path)
            return self.path
        except Exception as exc:
            if self.rollback_path.exists():
                os.replace(self.rollback_path, self.path)
            self.temp_path.unlink(missing_ok=True)
            raise ServiceStoreError(f"提交 Process Compose 配置失败：{exc}") from exc

    def finalize_prepared(self) -> None:
        try:
            self.rollback_path.unlink(missing_ok=True)
        except OSError:
            # A stale rollback file is harmless and will be recovered on restart.
            pass

    def rollback_prepared(self) -> None:
        try:
            if self.rollback_path.exists():
                os.replace(self.rollback_path, self.path)
            self.temp_path.unlink(missing_ok=True)
        except OSError as exc:
            raise ServiceStoreError(f"回滚 Process Compose 配置失败：{exc}") from exc

    def discard_prepared(self) -> None:
        try:
            self.temp_path.unlink(missing_ok=True)
        except OSError as exc:
            raise ServiceStoreError(f"清理 Process Compose 临时配置失败：{exc}") from exc

    def generate(self, services: Iterable[ServiceDefinition]) -> Path:
        self.prepare(services)
        self.commit_prepared()
        self.finalize_prepared()
        return self.path
